FROM python:alpine 

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything
COPY . .

# Expose port for the container
EXPOSE 8080

# Command to run the app
CMD ["uvicorn", "app.main:app", "--port", "8080"]


